services:
  api:
    image: ghcr.io/khw315/nyaasi-api-python:latest
    container_name: nyaa-api-server
    ports:
      - "8383:88"
    restart: unless-stopped
    dns:
      - 9.9.9.9
      - 149.112.112.112
      - 94.140.14.14
      - 94.140.15.15
    environment:
      - DOH_ENABLED=true
      - DOH_PROVIDER=quad9
